apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instant-pay-gateway-development
  annotations:
    argo.octopus.com/project: "Instant Pay Gateway"
    argo.octopus.com/environment: "development"
spec:
  project: default
  source:
     repoURL: https://github.com/OctopusSolutionsEngineering/ghu-instant-pay-gateway.git
     targetRevision: HEAD
     path: Kubernetes/Manifests/development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true