apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instant-pay-gateway-production
  annotations:
    argo.octopus.com/project: "Instant Pay Gateway"
    argo.octopus.com/environment: "production"
spec:
  project: default
  source:
     repoURL: https://github.com/OctopusSolutionsEngineering/ghu-instant-pay-gateway.git
     targetRevision: HEAD
     path: Kubernetes/Manifests/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true